"""Constants for the Spond Calendar integration."""

DOMAIN = "spond_calendar"

CONF_SPOND_EMAIL = "email"
CONF_SPOND_PASSWORD = "password"
CONF_GROUP_ID = "group_id"
CONF_GROUP_NAME = "group_name"
CONF_INCLUDE_PLANNED = "include_planned"
CONF_SHOW_UNANSWERED_INDICATOR = "show_unanswered_indicator"
CONF_UNANSWERED_PREFIX = "unanswered_prefix"
CONF_HIDE_DECLINED = "hide_declined"
CONF_UNANSWERED_REQUIRE_ALL = "unanswered_require_all"
CONF_HIDE_DECLINED_REQUIRE_ALL = "hide_declined_require_all"
CONF_STRIP_TITLE_EMOJI = "strip_title_emoji"
CONF_STRIP_DESCRIPTION_EMOJI = "strip_description_emoji"
CONF_USE_MEETUP_TIME_AS_DESCRIPTION = "use_meetup_time_as_description"

DEFAULT_SCAN_INTERVAL_MINUTES = 15
DEFAULT_DAYS_BACK = 14
DEFAULT_DAYS_AHEAD = 90
DEFAULT_INCLUDE_PLANNED = True
DEFAULT_SHOW_UNANSWERED_INDICATOR = True
DEFAULT_UNANSWERED_PREFIX = "❓"
DEFAULT_UNANSWERED_REQUIRE_ALL = False
DEFAULT_HIDE_DECLINED = True
DEFAULT_HIDE_DECLINED_REQUIRE_ALL = True
DEFAULT_STRIP_TITLE_EMOJI = True
DEFAULT_STRIP_DESCRIPTION_EMOJI = True
DEFAULT_USE_MEETUP_TIME_AS_DESCRIPTION = True
